name: CD Workflow

on:
    workflow_run:
        workflows: ["CI Workflow"]
        types: [completed]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v2

            - name: Execute remote SSH
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.PASSWORD }}
                port: ${{ secrets.PORT }}
                script: |
                    cd /github-action-demo
                    docker-compose pull
                    docker-compose up -d

         