name: CI Workflow

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest     # Github Runner (Free from github)
        steps:
            - name: checkout code
              uses: actions/checkout@v2
            
            - name: setup docker buildx
              uses: docker/setup-buildx-action@v4
